apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: backend-server
  namespace: team2-test
spec:
  replicas: 1
  selector:
    app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ezardhigh/mid2back:5
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: "production"
        - name: MYSQL_HOST
          value: "mybank-db.cxewkiaq63tk.ap-southeast-1.rds.amazonaws.com"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "mybank"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "alemvmfhwprxm2"
        - name: PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: team2-test
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000